version: '2.2'

services:
  app:
    build: .
    command: ["yarn", "dev"]
    tty: true
    stdin_open: true
    environment:
      - DB_URI=postgres://trails:trails@db:5432/trails
    volumes:
      - '.:/app'
      - /app/node_modules
    ports:
      - "3000:3000"